name: ArXiv Alert  
  
on:  
  schedule:  
    # Runs at 00:00 UTC everyday  
    - cron: "0 0 * * *"  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Setup Miniconda  
        uses: conda-incubator/setup-miniconda@v2  
        with:  
          activate-environment: arxiv-alert  
          python-version: 3.8  
          auto-activate-base: true  
  
      - name: Install dependencies  
        run: |  
          conda install pip  
          pip install --upgrade pip  
          pip install setuptools==57.5.0  
          pip install -r requirements.txt  
        shell: bash -l {0}  
  
      - name: Run ArXiv alert script  
        run: python arxiv.py  
        shell: bash -l {0}  
        env:  
          SENDER: ${{ secrets.SENDER }}  
          PASSWORD: ${{ secrets.PASSWORD }}  
          RECEIVERS: ${{ secrets.RECEIVERS }}  

